exports.Aladin = {
  category : [

    { linkClass: '1230', 	name: '가정/요리/뷰티',	subCategory: [
        { linkClass: '53471', 	name: '건강요리' },
        { linkClass: '53489', 	name: '결혼/가족' },
        { linkClass: '53476', 	name: '나라별 요리' },
        { linkClass: '53474', 	name: '다이어트 요리' },
        { linkClass: '53478', 	name: '도시락' },
        { linkClass: '53480', 	name: '디저트' },
        { linkClass: '53485', 	name: '뜨개질/바느질/DIY' },
        { linkClass: '53473', 	name: '사찰요리' },
        { linkClass: '53484', 	name: '살림/정리수납' },
        { linkClass: '53479', 	name: '샐러드/샌드위치' },
        { linkClass: '53472', 	name: '생활요리' },
        { linkClass: '53482', 	name: '술/음료/차' },
        { linkClass: '53487', 	name: '원예/조경/텃밭' },
        { linkClass: '53483', 	name: '음식 이야기' },
        { linkClass: '53477', 	name: '이유식' },
        { linkClass: '53475', 	name: '전문가/연예인/블로거 요리' },
        { linkClass: '53481', 	name: '제과제빵' },
        { linkClass: '53486', 	name: '집/인테리어' },
        { linkClass: '53488', 	name: '패션/뷰티' },
    ]},
    { linkClass: '55890', 	name: '건강/취미/레저',	subCategory: [
        { linkClass: '53516', 	name: '건강운동' },
        { linkClass: '53521', 	name: '건강정보' },
        { linkClass: '53522', 	name: '걷기/육상스포츠' },
        { linkClass: '53524', 	name: '골프' },
        { linkClass: '53532', 	name: '공예' },
        { linkClass: '161753', 	name: '글씨 쓰기' },
        { linkClass: '147647', 	name: '스티커북' },
        { linkClass: '114987', 	name: '컬러링북' },
        { linkClass: '53525', 	name: '구기' },
        { linkClass: '53528', 	name: '낚시' },
        { linkClass: '53514', 	name: '다이어트' },
        { linkClass: '53520', 	name: '대체의학' },
        { linkClass: '53529', 	name: '등산/캠핑' },
        { linkClass: '53526', 	name: '무예/무술' },
        { linkClass: '53530', 	name: '바둑/장기' },
        { linkClass: '53534', 	name: '반려동물' },
        { linkClass: '53523', 	name: '수영/수상스포츠' },
        { linkClass: '53527', 	name: '스포츠/레저 기타' },
        { linkClass: '53533', 	name: '원예' },
        { linkClass: '140262', 	name: '재난/생존/서바이벌' },
        { linkClass: '53517', 	name: '정신건강' },
        { linkClass: '53518', 	name: '질병치료와 예방' },
        { linkClass: '53535', 	name: '취미기타' },
        { linkClass: '53531', 	name: '퍼즐/스도쿠/퀴즈' },
        { linkClass: '53519', 	name: '한의학' },
        { linkClass: '53515', 	name: '헬스/피트니스' },
    ]},
    { linkClass: '170', 	name: '경제경영',	subCategory: [
        { linkClass: '3057', 	name: '경제학/경제일반' },
        { linkClass: '2172', 	name: '기업 경영' },
        { linkClass: '2028', 	name: '기업/경영자 스토리' },
        { linkClass: '261', 	name: '마케팅/세일즈' },
        { linkClass: '172', 	name: '재테크/투자' },
        { linkClass: '177', 	name: '창업/취업/은퇴' },
        { linkClass: '3049', 	name: 'CEO/비즈니스맨을 위한 능력계발' },
    ]},
    { linkClass: '2105', 	name: '고전',	subCategory: [
        { linkClass: '2330', 	name: '경제학고전' },
        { linkClass: '4527', 	name: '고사성어/속담' },
        { linkClass: '2094', 	name: '고전에서배운다' },
        { linkClass: '2344', 	name: '과학고전' },
        { linkClass: '2310', 	name: '군사고전' },
        { linkClass: '2095', 	name: '다시쓴고전' },
        { linkClass: '2123', 	name: '동양고전문학' },
        { linkClass: '2124', 	name: '동양고전사상' },
        { linkClass: '2125', 	name: '서양고전문학' },
        { linkClass: '2126', 	name: '서양고전사상' },
        { linkClass: '2121', 	name: '우리나라 옛글' },
        { linkClass: '7459', 	name: '위대한 작가들' },
    ]},
    { linkClass: '987', 	name: '과학',	subCategory: [
        { linkClass: '51002', 	name: '기초과학/교양과학' },
        { linkClass: '51005', 	name: '과학의 이해' },
        { linkClass: '51007', 	name: '과학사회학(STS)' },
        { linkClass: '51010', 	name: '과학자의 생애' },
        { linkClass: '51013', 	name: '뇌과학' },
        { linkClass: '51015', 	name: '생명과학' },
        { linkClass: '51017', 	name: '인체의 이해' },
        { linkClass: '51272', 	name: '의학' },
        { linkClass: '51275', 	name: '법의학' },
        { linkClass: '51022', 	name: '동물과 식물' },
        { linkClass: '51024', 	name: '물리학' },
        { linkClass: '51027', 	name: '천문학' },
        { linkClass: '51030', 	name: '지구과학' },
        { linkClass: '51033', 	name: '수학' },
        { linkClass: '51035', 	name: '화학' },
        { linkClass: '51038', 	name: '공학' },
        { linkClass: '51039', 	name: '세계의 불가사의' },
        { linkClass: '51043', 	name: '발명/발견' },
        { linkClass: '51045', 	name: '농업' },
    ]},
    { linkClass: '8257', 	name: '대학교재',	subCategory: [
        { linkClass: '8261', 	name: '경상계열' },
        { linkClass: '8262', 	name: '공학계열' },
        { linkClass: '8263', 	name: '농축산생명계열' },
        { linkClass: '8264', 	name: '법학계열' },
        { linkClass: '8265', 	name: '사범계열' },
        { linkClass: '8259', 	name: '사회과학계열' },
        { linkClass: '8267', 	name: '생활환경계열' },
        { linkClass: '8266', 	name: '어문학계열' },
        { linkClass: '8725', 	name: '연감' },
        { linkClass: '8269', 	name: '예체능계열' },
        { linkClass: '8268', 	name: '의약학간호계열' },
        { linkClass: '8258', 	name: '인문계열' },
        { linkClass: '8260', 	name: '자연과학계열' },
        { linkClass: '8724', 	name: '전문사전' },
        { linkClass: '164281',name: '한국방송통신대학교' },
    ]},
    { linkClass: '2551', 	name: '만화',	subCategory: [
        // { linkClass: '69397', 	name: '캐릭터상품' },
        { linkClass: '4668', 	name: '교양만화' },
        { linkClass: '36192', name: '그래픽노블' },
        { linkClass: '3751', 	name: '대하/서사만화' },
        { linkClass: '3726', 	name: '만화그리기와 읽기' },
        { linkClass: '3728', 	name: '본격장르만화' },
        { linkClass: '2562', 	name: '성인/성애만화' },
        { linkClass: '3727', 	name: '소년만화' },
        { linkClass: '3741', 	name: '순정만화' },
        { linkClass: '2561', 	name: '스포츠만화' },
        { linkClass: '3936', 	name: '동물만화' },
        { linkClass: '3949', 	name: '유럽/서구만화' },
        { linkClass: '3750', 	name: '요리만화' },
        { linkClass: '3749', 	name: '직장인만화' },
        { linkClass: '3747', 	name: '가족만화' },
        { linkClass: '3748', 	name: '논픽션/휴먼만화' },
        { linkClass: '9680', 	name: '인디만화' },
        { linkClass: '7443', 	name: '인터넷 연재 만화' },
        { linkClass: '2552', 	name: '코믹/명랑만화' },
        // { linkClass: '134823', 	name: '19금' },
    ]},
    { linkClass: '798', 	name: '사회과학',	subCategory: [
        { linkClass: '50992', 	name: '비평/칼럼' },
        { linkClass: '50995', 	name: '사회문제' },
        { linkClass: '50997', 	name: '환경/생태문제' },
        { linkClass: '50999', 	name: '교육학' },
        { linkClass: '51001', 	name: '사회운동' },
        { linkClass: '51004', 	name: '사회사상/사회사상사' },
        { linkClass: '51008', 	name: '미래학' },
        { linkClass: '51011', 	name: '지리학/지정학' },
        { linkClass: '51016', 	name: '정치학/외교학/행정학' },
        { linkClass: '51021', 	name: '한국정치사정/정치사' },
        { linkClass: '51026', 	name: '사회학' },
        { linkClass: '51037', 	name: '여성학/젠더' },
        { linkClass: '51041', 	name: '언론/미디어' },
        { linkClass: '51046', 	name: '법과 생활' },
        { linkClass: '51048', 	name: '통일/북한관계' },
        { linkClass: '51050', 	name: '국방/군사학' },
        { linkClass: '51052', 	name: '계간지/무크' },
    ]},
    { linkClass: '1', 	name: '소설/시/희곡',	subCategory: [
        { linkClass: '50917', 	name: '한국소설' },
        { linkClass: '50918', 	name: '일본소설' },
        { linkClass: '50919', 	name: '영미소설' },
        { linkClass: '50920', 	name: '스페인/중남미소설' },
        { linkClass: '50921', 	name: '프랑스소설' },
        { linkClass: '50922', 	name: '독일소설' },
        { linkClass: '50923', 	name: '중국소설' },
        { linkClass: '52650', 	name: '러시아소설' },
        { linkClass: '50925', 	name: '세계의 소설' },
        { linkClass: '50926', 	name: '추리/미스터리소설' },
        { linkClass: '50927', 	name: '라이트 노벨' },
        { linkClass: '50928', 	name: '판타지/환상문학' },
        { linkClass: '50929', 	name: '역사소설' },
        { linkClass: '50930', 	name: '과학소설(SF)' },
        { linkClass: '50931', 	name: '호러.공포소설' },
        { linkClass: '50932', 	name: '무협소설' },
        { linkClass: '50933', 	name: '액션/스릴러소설' },
        { linkClass: '50935', 	name: '로맨스소설' },
        { linkClass: '50940', 	name: '시' },
        { linkClass: '50942', 	name: '신춘문예작품집' },
        { linkClass: '50943', 	name: '우리나라 옛글' },
        { linkClass: '50945', 	name: '문학의 이해' },
        { linkClass: '50948', 	name: '희곡' },
        { linkClass: '50951', 	name: '문학 잡지' },
        { linkClass: '51252', 	name: '여성문학' },
        { linkClass: '50953', 	name: '테마문학' },
        { linkClass: '50955', 	name: '세계의 문학' },
    ]},
    { linkClass: '55889', 	name: '에세이',	subCategory: [
        { linkClass: '51371', 	name: '한국에세이' },
        { linkClass: '51373', 	name: '외국에세이' },
        { linkClass: '174700', 	name: '동물에세이' },
        { linkClass: '51374', 	name: '명상에세이' },
        { linkClass: '51375', 	name: '심리치유 에세이' },
        { linkClass: '51376', 	name: '사진/그림 에세이' },
        { linkClass: '180236', 	name: '음식에세이' },
        { linkClass: '51377', 	name: '여행에세이' },
        { linkClass: '51380', 	name: '독서에세이' },
        { linkClass: '51842', 	name: '예술에세이' },
        { linkClass: '51389', 	name: '종교에세이' },
        { linkClass: '51391', 	name: '사랑/연애 에세이' },
        { linkClass: '51392', 	name: '노년을 위한 에세이' },
        { linkClass: '51394', 	name: '자연에세이' },
        { linkClass: '51398', 	name: '명언/잠언록' },
        { linkClass: '51402', 	name: '일기/편지' },
        { linkClass: '51404', 	name: '유머/풍자/우화' },
        { linkClass: '51408', 	name: '포켓에세이' },
        { linkClass: '51413', 	name: '작은 이야기 모음' },
        { linkClass: '51416', 	name: '명사에세이' },
    ]},
    { linkClass: '1108', 	name: '어린이',	subCategory: [
        { linkClass: '48904', 	name: '초등 한국사' },
        { linkClass: '48803', 	name: '초등1~2학년' },
        { linkClass: '48804', 	name: '초등3~4학년' },
        { linkClass: '48805', 	name: '초등5~6학년' },
        { linkClass: '48808', 	name: '초등 전학년' },
        { linkClass: '48806', 	name: '교과서 수록도서' },
        { linkClass: '48810', 	name: '동화/명작/고전' },
        { linkClass: '48814', 	name: '아동 문학론' },
        { linkClass: '48809', 	name: '과학/수학/컴퓨터' },
        { linkClass: '48813', 	name: '사회/역사/철학' },
        { linkClass: '48812', 	name: '문화/예술/인물' },
        { linkClass: '48817', 	name: '어린이 영어' },
        { linkClass: '48819', 	name: '어린이 한자' },
        { linkClass: '49179', 	name: '어린이 중국어' },
        { linkClass: '48820', 	name: '책읽기/글쓰기' },
        { linkClass: '48815', 	name: '어린이 사전/도감' },
        { linkClass: '48821', 	name: 'TV/만화/영화' },
        { linkClass: '139408', 	name: '게임 만화/캐릭터도감' },
        { linkClass: '112080', 	name: '학습만화' },
    ]},
    { linkClass: '13789', 		name: '유아',	subCategory: [
        { linkClass: '70125', 	name: '주제별 책읽기' },
        { linkClass: '35088', 	name: '0~3세' },
        { linkClass: '35089', 	name: '4~7세' },
        { linkClass: '73222', 	name: '100세까지 보는 그림책' },
        { linkClass: '35091', 	name: '그림책' },
        { linkClass: '35092', 	name: '놀이책' },
        { linkClass: '35094', 	name: '유아 교양/학습' },
        { linkClass: '4298', 		name: '애니메이션/캐릭터' },
        { linkClass: '88620', 	name: '유아 워크북' },
        { linkClass: '69170', 	name: '유아 세트' },
        { linkClass: '131949', 	name: '예비초등' },
    ]},
    { linkClass: '1196', 	name: '여행',	subCategory: [
        { linkClass: '50827', 	name: '국내 여행에세이' },
        { linkClass: '50828', 	name: '서울/수도권 여행가이드' },
        { linkClass: '50829', 	name: '제주도 여행가이드' },
        { linkClass: '50830', 	name: '국내 여행가이드' },
        { linkClass: '73807', 	name: '캠핑여행' },
        { linkClass: '63679', 	name: '미국여행' },
        { linkClass: '63682', 	name: '캐나다여행' },
        { linkClass: '50837', 	name: '중남미여행' },
        { linkClass: '50831', 	name: '유럽여행' },
        { linkClass: '110284', 	name: '북유럽여행' },
        { linkClass: '110285', 	name: '동유럽여행' },
        { linkClass: '63847', 	name: '프랑스여행' },
        { linkClass: '63634', 	name: '영국여행' },
        { linkClass: '63688', 	name: '스페인여행' },
        { linkClass: '63849', 	name: '독일여행' },
        { linkClass: '63942', 	name: '이탈리아여행' },
        { linkClass: '63980', 	name: '터키여행' },
        { linkClass: '64448', 	name: '중동여행' },
        { linkClass: '50839', 	name: '아프리카여행' },
        { linkClass: '50832', 	name: '일본여행' },
        { linkClass: '50833', 	name: '중국여행' },
        { linkClass: '63512', 	name: '홍콩/대만/마카오여행' },
        { linkClass: '50834', 	name: '동남아시아여행' },
        { linkClass: '63828', 	name: '호주/뉴질랜드여행' },
        { linkClass: '63860', 	name: '인도/티베트/네팔여행' },
        { linkClass: '63975', 	name: '괌/사이판/하와이여행' },
        { linkClass: '63977', 	name: '발리/몰디브여행' },
        { linkClass: '50840', 	name: '세계일주여행' },
        { linkClass: '50842', 	name: '테마여행' },
        { linkClass: '50841', 	name: '기타지역여행' },
        { linkClass: '50845', 	name: '유학/해외연수/이민' },
        { linkClass: '50844', 	name: '워킹 홀리데이' },
        { linkClass: '50843', 	name: '지도' },
    ]},
    { linkClass: '74', 	name: '역사',	subCategory: [
        { linkClass: '1628', 	name: '동양사일반' },
        { linkClass: '147', 	name: '북한사' },
        { linkClass: '75', 		name: '역사학' },
        { linkClass: '52593', name: '한국사 일반' },
        { linkClass: '109', 	name: '한국고대~고려시대' },
        { linkClass: '52589', name: '조선사' },
        { linkClass: '52590', name: '한국근현대사' },
        { linkClass: '52594', name: '중국사' },
        { linkClass: '52595', name: '일본사' },
        { linkClass: '148', 	name: '아시아사' },
        { linkClass: '5242', 	name: '서양사' },
        { linkClass: '159', 	name: '유럽사' },
        { linkClass: '5029', 	name: '아메리카사' },
        { linkClass: '5027', 	name: '아프리카/오세아니아사' },
        { linkClass: '52606', name: '이슬람/중동/이스라엘' },
        { linkClass: '169', 	name: '세계사 일반' },
        { linkClass: '52610', name: '전쟁/분쟁사' },
        { linkClass: '81', 		name: '테마로 보는 역사' },
        { linkClass: '78', 		name: '고고학' },
        { linkClass: '2177', 	name: '문화/역사기행' },
        { linkClass: '3266', 	name: '학회/무크/계간지' },
    ]},
    { linkClass: '517', 	name: '예술/대중문화',	subCategory: [
        // { linkClass: '114988', 	name: '컬러링북' },
        { linkClass: '50950', 	name: '예술/대중문화의 이해' },
        { linkClass: '50965', 	name: '미술' },
        { linkClass: '50966', 	name: '음악' },
        { linkClass: '50967', 	name: '영화/드라마' },
        { linkClass: '50968', 	name: '사진' },
        { linkClass: '50969', 	name: '건축' },
        { linkClass: '50970', 	name: '뮤지컬/오페라' },
        { linkClass: '50971', 	name: '예술경영/공연기획' },
        { linkClass: '50972', 	name: '디자인/공예' },
        { linkClass: '50973', 	name: '무용' },
        { linkClass: '50974', 	name: '연극' },
        { linkClass: '50975', 	name: 'TV/라디오' },
        { linkClass: '50976', 	name: '미술/음악/예술치료' },
    ]},
    { linkClass: '1322', 	name: '외국어',	subCategory: [
        { linkClass: '8723', 		name: '어학사전' },
        { linkClass: '49846', 	name: '토익' },
        { linkClass: '49847', 	name: '텝스' },
        { linkClass: '49848', 	name: '토플' },
        { linkClass: '49845', 	name: '영어회화' },
        { linkClass: '49874', 	name: '영어시험대비' },
        { linkClass: '49834', 	name: '영문법' },
        { linkClass: '49835', 	name: '영어독해' },
        { linkClass: '49833', 	name: '영어학습법' },
        { linkClass: '49838', 	name: '영어어휘' },
        { linkClass: '49949', 	name: '영작문' },
        { linkClass: '49837', 	name: '영어듣기/말하기' },
        { linkClass: '49873', 	name: 'OPIc/인터뷰 영어' },
        { linkClass: '49839', 	name: '영어사전' },
        { linkClass: '49884', 	name: '일본어' },
        { linkClass: '49903', 	name: '중국어' },
        { linkClass: '49904', 	name: '한자' },
        { linkClass: '49905', 	name: '독일어' },
        { linkClass: '49930', 	name: '러시아어' },
        { linkClass: '49929', 	name: '스페인어' },
        { linkClass: '49931', 	name: '이탈리아어' },
        { linkClass: '49906', 	name: '프랑스어' },
        { linkClass: '49933', 	name: '기타 서양어' },
        { linkClass: '49932', 	name: '기타 동양어' },
        { linkClass: '49908', 	name: '외국인을 위한 한국어' },
        { linkClass: '49909', 	name: '통역/번역' },
    ]},
    { linkClass: '656', 	name: '인문학',	subCategory: [
        { linkClass: '65237', 	name: '사상가/인문학자' },
        { linkClass: '51378', 	name: '교양 인문학' },
        { linkClass: '51381', 	name: '인문 에세이' },
        { linkClass: '51384', 	name: '인문 비평' },
        { linkClass: '51385', 	name: '인문학 전문사전' },
        { linkClass: '51387', 	name: '철학 일반' },
        { linkClass: '51390', 	name: '서양철학' },
        { linkClass: '51393', 	name: '동양철학' },
        { linkClass: '51395', 	name: '심리학/정신분석학' },
        { linkClass: '51399', 	name: '신화/종교학' },
        { linkClass: '51403', 	name: '책읽기/글쓰기' },
        { linkClass: '51405', 	name: '서지/출판' },
        { linkClass: '51409', 	name: '기호학/언어학' },
        { linkClass: '51412', 	name: '논리와 비판적 사고' },
        { linkClass: '51415', 	name: '인류학/고고학' },
        { linkClass: '51417', 	name: '문화/문화이론' },
        { linkClass: '51419', 	name: '학회/무크/계간지' },
    ]},
    { linkClass: '336', 	name: '자기계발',	subCategory: [
        { linkClass: '70214', 	name: '성공' },
        { linkClass: '70212', 	name: '리더십' },
        { linkClass: '70211', 	name: '행복론' },
        { linkClass: '2951', 		name: '인간관계' },
        { linkClass: '70236', 	name: '힐링' },
        { linkClass: '107822', 	name: '정리/심플라이프' },
        { linkClass: '70224', 	name: '협상/설득/화술' },
        { linkClass: '70233', 	name: '프레젠테이션/회의' },
        { linkClass: '70228', 	name: '기획/보고' },
        { linkClass: '70220', 	name: '시간관리/정보관리' },
        { linkClass: '70223', 	name: '창의적사고/두뇌계발' },
        { linkClass: '2943', 		name: '취업/진로/유망직업' },
        { linkClass: '70241', 	name: '20대의 자기계발' },
        { linkClass: '70218', 	name: '여성의 자기계발' },
        { linkClass: '70219', 	name: '중년의 자기계발' },
    ]},
    { linkClass: '112011', 	name: '장르소설',	subCategory: [
        { linkClass: '50926', 	name: '추리/미스터리소설' },
        { linkClass: '50927', 	name: '라이트 노벨' },
        { linkClass: '50928', 	name: '판타지/환상문학' },
        { linkClass: '50930', 	name: '과학소설(SF)' },
        { linkClass: '50931', 	name: '호러.공포소설' },
        { linkClass: '50932', 	name: '무협소설' },
        { linkClass: '50933', 	name: '액션/스릴러소설' },
        { linkClass: '50935', 	name: '로맨스소설' },
    ]},

    { linkClass: '1237', 	name: '종교/역학',	subCategory: [
        { linkClass: '51564', 	name: '기독교(개신교)' },
        { linkClass: '51565', 	name: '가톨릭' },
        { linkClass: '51566', 	name: '불교' },
        { linkClass: '51567', 	name: '세계의 종교' },
        { linkClass: '51568', 	name: '역학' },
        { linkClass: '51569', 	name: '명상/선' },
        { linkClass: '51570', 	name: '종교일반' },
    ]},
    { linkClass: '2030', 	name: '좋은부모',	subCategory: [
        { linkClass: '73196', 	name: '부모교육' },
        { linkClass: '51762', 	name: '임신/출산' },
        { linkClass: '51770', 	name: '태교' },
        { linkClass: '51763', 	name: '영유아 육아' },
        { linkClass: '51764', 	name: '초등 자녀' },
        { linkClass: '51766', 	name: '육아' },
        { linkClass: '51789', 	name: '건강/환경' },
        { linkClass: '51767', 	name: '교육/학습' },
        { linkClass: '51801', 	name: '특수교육' },
        { linkClass: '7259', 		name: '사춘기/성교육' },
        { linkClass: '51790', 	name: '육아/교육 에세이' },
    ]},
    { linkClass: '1137', 	name: '청소년',	subCategory: [
        { linkClass: '9671', 	name: '청소년 경제' },
        { linkClass: '36379', name: '중등교육과정' },
        { linkClass: '36380', name: '고등교육과정' },
        { linkClass: '4621', 	name: '학습법' },
        { linkClass: '1147', 	name: '논술참고도서' },
        { linkClass: '1146', 	name: '수능시험성공수기' },
        { linkClass: '50758', name: '청소년 문학' },
        { linkClass: '1140', 	name: '청소년 역사' },
        { linkClass: '2012', 	name: '청소년의 진로선택' },
        { linkClass: '2574', 	name: '청소년과 성(性)' },
        { linkClass: '7268', 	name: '청소년 고전' },
        { linkClass: '1143', 	name: '청소년 수학/과학' },
        { linkClass: '4410', 	name: '청소년 영어' },
        { linkClass: '1141', 	name: '청소년 문화/예술' },
        { linkClass: '32399', name: '청소년 자기계발' },
        { linkClass: '1139', 	name: '청소년 철학' },
        { linkClass: '1142', 	name: '청소년 인문/사회' },
        { linkClass: '32663', name: '청소년 인물' },
        { linkClass: '28969', name: '청소년의 사회생활' },
        { linkClass: '1149', 	name: '청소년이 쓴 책' },
    ]},
    { linkClass: '351', 	name: '컴퓨터/모바일',	subCategory: [
        { linkClass: '2630', 	name: '그래픽/멀티미디어' },
        { linkClass: '55977', name: '모바일 프로그래밍' },
        { linkClass: '55055', name: '스마트폰/태블릿/SNS' },
        { linkClass: '2599', 	name: '오피스(엑셀/파워포인트)' },
        { linkClass: '6348', 	name: '웹디자인/홈페이지' },
        { linkClass: '128622',name: '초중고 소프트웨어 교육/코딩' },
        { linkClass: '2719', 	name: '컴퓨터 공학' },
        { linkClass: '7396', 	name: '프로그래밍 개발/방법론' },
        { linkClass: '437', 	name: '프로그래밍 언어' },
        { linkClass: '479', 	name: '활용능력' },
        { linkClass: '2349', 	name: 'e비즈니스/창업' },
        { linkClass: '363', 	name: 'OS/Networking' },
        { linkClass: '2613', 	name: 'PC/게임/디지털 카메라' },
    ]},
  ]
}